services:
  affine:
    container_name: affine
    image: ghcr.io/toeverything/affine:0.26.3
    expose:
      - 3010
    networks:
      - t3_proxy
      - internal
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - ${CONTAINERSDIR}/affine/upload:/root/.affine/storage
      - ${CONTAINERSDIR}/affine/config:/root/.affine/config
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=${AFFINE_DB_URL}
      - AFFINE_INDEXER_ENABLED=false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.affine-rtr.entrypoints=websecure-internal,websecure-external"
      - "traefik.http.routers.affine-rtr.rule=Host(`affine.$DOMAINNAME`)"
      # HTTP Services
      - "traefik.http.routers.affine-rtr.service=affine-svc"
      - "traefik.http.services.affine-svc.loadbalancer.server.port=3010"
      # Middlewares
      - "traefik.http.routers.affine-rtr.middlewares=chain-no-auth@file"

  affine_migration:
    image: ghcr.io/toeverything/affine:0.26.3
    container_name: affine_migration
    volumes:
      # custom configurations
      - ${CONTAINERSDIR}/affine/upload:/root/.affine/storage
      - ${CONTAINERSDIR}/affine/config:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=${AFFINE_DB_URL}
      - AFFINE_INDEXER_ENABLED=false
    networks:
      - internal
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - internal
