services:
  lncrawl:
    container_name: lncrawl
    image: ghcr.io/lncrawl/lightnovel-crawler:latest
    restart: unless-stopped
    expose:
      - 8080
    command: -ll server
    environment:
      PYTHONUNBUFFERED: "1"
      PUID: ${PUID}
      PGID: ${PGID}      
      LNCRAWL_DATA_PATH: /data
      DATABASE_URL: postgresql+psycopg://hackmonker:IAMHERO@postgres:5432/lncrawl
    volumes:
      - ${CONTAINERSDIR}/lncrawl:/data
      - /mnt/local/downloads/temp/lncrawl:/data/novels
    depends_on:
      - postgres
    networks:
      - t3_proxy
      - internal
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.lncrawl-rtr.entrypoints=websecure-internal,websecure-external"
      - "traefik.http.routers.lncrawl-rtr.rule=Host(`lncrawl.$DOMAINNAME`)"
      # HTTP Services
      - "traefik.http.routers.lncrawl-rtr.service=lncrawl-svc"
      - "traefik.http.services.lncrawl-svc.loadbalancer.server.port=8080"
      # Middlewares
      - "traefik.http.routers.lncrawl-rtr.middlewares=chain-no-auth@file"