services:
  organize:
    image: hackmonker/organize:main
    container_name: organize
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      - HOME=/tmp
      - WATCH_DIRS=${WATCH_DIRS}
      - ORGANIZE_CONFIG=/organize/config.yml
      - LOG_FILE=/organize/organizer.log
      - DEBOUNCE_SECONDS=15
    volumes:
      - ${CONTAINERSDIR}/organize:/organize
      - /mnt:/mnt
      - /opt:/opt