services:
  tgfiles:
    container_name: tgfiles
    image: ghcr.io/jarvis2f/telegram-files:latest
    restart: always
    # Uncomment the following lines to enable health check for the service.
    #    depends_on:
    #      telegram-files-postgres:
    #        condition: service_healthy
    #      telegram-files-mysql:
    #        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1/api/health" ]
      interval: 10s
      retries: 3
      timeout: 10s
      start_period: 10s
    environment:
      # PUID and PGID are the user id and group id of the user who owns the files in the mounted volume.
      PUID: ${PUID}
      PGID: ${PGID}
      #NGINX_PORT: 80
      APP_ENV: "prod"
      APP_ROOT: "/app/data"
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      # Uncomment the following lines to enable database connection, you can see .env.example for more details.
      #DB_TYPE: ${DB_TYPE}
      #DB_HOST: ${DB_HOST}
      #DB_PORT: ${DB_PORT}
      #DB_USER: ${DB_USER}
      #DB_PASSWORD: ${DB_PASSWORD}
      #DB_NAME: ${DB_NAME}
    expose:
      - 80
    networks:
      - t3_proxy
    volumes:
      - ${CONTAINERSDIR}/tgfiles:/app/data
      - ${TEMPDIR}/tgfiles:/app/other-files-for-transfer
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.tgfiles-rtr.entrypoints=websecure-internal,websecure-external"
      - "traefik.http.routers.tgfiles-rtr.rule=Host(`tgfiles.$DOMAINNAME`)"
      # HTTP Services
      - "traefik.http.routers.tgfiles-rtr.service=tgfiles-svc"
      - "traefik.http.services.tgfiles-svc.loadbalancer.server.port=80"
      # Middlewares
      - "traefik.http.routers.tgfiles-rtr.middlewares=chain-no-auth@file"