services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    security_opt:
      - no-new-privileges:true
    expose:
       - 80
    networks:
      - t3_proxy
    user: ${PUID}:${PGID}
    environment:
      - TZ=Asia/Kolkata
      - ADMIN_TOKEN=${VAULTWARDEN_TOKEN}
      - DATABASE_URL=${VAULTWARDEN_DB_URL}
      - DOMAIN=https://vaultwarden.${DOMAINNAME}
    depends_on:
      - postgres
    volumes:
       - ${CONTAINERSDIR}/vaultwarden/app:/data
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.vaultwarden-rtr.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-rtr.rule=Host(`vaultwarden.$DOMAINNAME`)"
      # HTTP Services
      - "traefik.http.routers.vaultwarden-rtr.service=vaultwarden-svc"
      - "traefik.http.services.vaultwarden-svc.loadbalancer.server.port=80"
      # Middlewares
      - "traefik.http.routers.vaultwarden-rtr.middlewares=chain-no-auth@file"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-vaultwarden
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${CONTAINERSDIR}/vaultwarden/database:/var/lib/postgresql/18/data
