services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    volumes:
      - ${CONTAINERSDIR}/backrest/data:/data
      - ${CONTAINERSDIR}/backrest/config:/config
      - ${CONTAINERSDIR}/backrest/cache:/cache
      - /home/hackmonker/.config/rclone:/root/.config/rclone
      - /opt:/opt
      # - /MY-backrest-DATA:/userdata # [optional] mount local paths to backrest here.
      # - /MY-REPOS:/repos # [optional] mount repos if using local storage, not necessary for remotes e.g. B2, S3, etc.
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=America/Los_Angeles # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    expose:
      - 9898
    networks:
      - t3_proxy
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.backrest-rtr.entrypoints=websecure-internal,websecure-external"
      - "traefik.http.routers.backrest-rtr.rule=Host(`backup.$DOMAINNAME`)"
      # HTTP Services
      - "traefik.http.routers.backrest-rtr.service=backrest-svc"
      - "traefik.http.services.backrest-svc.loadbalancer.server.port=9898"
      # Middlewares
      - "traefik.http.routers.backrest-rtr.middlewares=chain-authentik@file"